serenity.project.name=Serenity and Cucumber Quick Start


serenity.browser.maximized = true
webdriver.manage.window.maximize=true
headless.mode=false
serenity.console.colors = true
serenity.step.delay=750

